name: pre-commit
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  pre-commit:
    name: pre-commit
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4.1.2
      - name: pre-commit
        uses: pre-commit/action@v3.0.1
